#!/bin/bash
# deploy_github.sh — Deploy static site to GitHub Pages (FREE)
# Args: $1=slug
# Loads GITHUB_TOKEN and GITHUB_USERNAME from .env

set -e

SLUG="$1"
if [ -z "$SLUG" ]; then
  echo "ERROR: Missing slug argument"
  exit 1
fi

ENV_FILE="$HOME/france-leads-automation/.env"
if [ -f "$ENV_FILE" ]; then
  source "$ENV_FILE"
fi

if [ -z "$GITHUB_TOKEN" ] || [ -z "$GITHUB_USERNAME" ]; then
  echo "❌ ERROR: GITHUB_TOKEN and GITHUB_USERNAME must be set in $ENV_FILE"
  exit 1
fi

REPO_NAME="${SLUG}-site"
SITE_DIR="$HOME/france-leads-automation/sites/$SLUG/public-site"
OUT_DIR="$SITE_DIR/out"

if [ ! -f "$OUT_DIR/index.html" ]; then
  echo "❌ ERROR: out/index.html not found at $OUT_DIR"
  exit 1
fi

echo ""
echo "═══════════════════════════════════════════════"
echo "  Deploying: $REPO_NAME → GitHub Pages"
echo "═══════════════════════════════════════════════"

cd "$OUT_DIR"

# Initialize git
rm -rf .git
git init
git config user.email "automation@leads.fr"
git config user.name "France Leads Bot"

# Create .nojekyll (required for GitHub Pages with Next.js paths)
touch .nojekyll

# Create proper gitignore for out folder
cat > .gitignore << 'GITEOF'
node_modules/
.env
.env.local
*.db
GITEOF

git add -A
git commit -m "feat: $SLUG website — auto-generated by France Leads"

# Set remote with token auth
git remote add origin "https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$REPO_NAME.git" 2>/dev/null \
  || git remote set-url origin "https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$REPO_NAME.git"

# Create repo via GitHub CLI or API
echo "→ Creating GitHub repository: $REPO_NAME"
gh repo create "$GITHUB_USERNAME/$REPO_NAME" --public 2>/dev/null || echo "  Repo may already exist, continuing..."

# Push
echo "→ Pushing to GitHub..."
git push -u origin main --force

# Enable GitHub Pages via API
echo "→ Enabling GitHub Pages..."
curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$GITHUB_USERNAME/$REPO_NAME/pages" \
  -d '{"source":{"branch":"main","path":"/"}}' > /dev/null 2>&1 || true

# Also try updating pages config if already exists
curl -s -X PUT \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$GITHUB_USERNAME/$REPO_NAME/pages" \
  -d '{"source":{"branch":"main","path":"/"}}' > /dev/null 2>&1 || true

GITHUB_URL="https://$GITHUB_USERNAME.github.io/$REPO_NAME"
echo "→ GitHub Pages URL: $GITHUB_URL"
echo "→ Waiting 90 seconds for GitHub Pages to deploy..."
sleep 90

# Verify deployment
STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$GITHUB_URL" 2>/dev/null || echo "000")
if [ "$STATUS" = "200" ] || [ "$STATUS" = "301" ] || [ "$STATUS" = "302" ]; then
  echo "✅ Site LIVE at: $GITHUB_URL"
else
  echo "⚠️  Site may still be deploying (HTTP $STATUS). URL: $GITHUB_URL"
  sleep 30
fi

echo "$GITHUB_URL"
